services:
  - type: web
    name: get-obd-explanation
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        fromDatabase: OPENAI_API_KEY
